### ISSUE TITLE
Add "Enable flash/torch" button 

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#107]
### Proposed changes 

Change `const constraints` to `var`.

Then proceed with something like this:
````js
 var imageCaptureConfig = {
        fillLightMode: "torch", /* or "flash" */
        focusMode: "continuous"
    };
````
(Source: https://stackoverflow.com/questions/37848494/is-it-possible-to-control-the-camera-light-on-a-phone-via-a-website)

Note: This only works on _some_ Android phones.

### Tasks
- [x] Basic implementation with icon 
- [x] Make sure this only is shown on supported mobile devices (exclude iOS!)

**Comment by gitgauner** [comment]
Let's not prioritize this to v2.x, as it works only on some devices.

**Comment by philipbrembeck** [comment]
- Icon !
