### ISSUE TITLE
[BUG] OpenGraph 'title' property doesn't get translated

### ISSUE THREAD

**Issue by lwojcik** [frontendnetwork/veganify#305]
## Bug description

OpenGraph meta title in all language versions remains the same (German):

```html
<meta property="og:title" content="Ist es Vegan? - Vegan Check"/>
```

It would be great if OG title remained consistent with HTML title.

### Steps to reproduce 

1. Open https://vegancheck.me/ and copy the URL (any language version except German)
2. Try sharing the URL on any social media that consumes OpenGraph tags (fediverse, Twitter, LinkedIn...)
3. German title is visible in the link preview

Most likely all it takes is putting ```{t("title")}``` [in this line](https://github.com/frontendnetwork/vegancheck.me/blob/5d23d2fb0326b5a00b26c6771379dc8fce6402e7/src/components/nav.tsx#LL35C24-L35C24).

I'll test the fix in the evening and open a PR if it proves to be enough.

**Comment by philipbrembeck** [comment]
Yes, that is the case. Will do this after the maintance work is done:)

**Comment by philipbrembeck** [comment]
Fixed now 😊
