### ISSUE TITLE
[Cache bug] iOS icons don't change

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#42]
**Describe the bug**
Although a new icon was introduced, it is not loaded by iOS. 

**To Reproduce**
1. Tap on "Add to homescreen"
2. Preview shows the old icon (v1.1.0)
3. Tap on "Add to Homescreen" again
4. Homescreen shows the old icon

**Expected behavior**
Display icon v2.0.0 on homescreen & preview.

**Desktop (please complete the following information):**
 - OS: iOS 15.1.1
 - Browser: Safari 15.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.1.1
 - Browser: Safari

**Additional context**
@gitgauner please check the caches

**Comment by gitgauner** [comment]
Clodflare cache's now in development mode @philipbrembeck

**Comment by philipbrembeck** [comment]
Would you mind throwing it in Lambdatest real quick?

**Comment by gitgauner** [comment]
iPhone 11, iOS 13.3 (nothing newer available):
<img src="https://i.ibb.co/n1mLkTj/Bildschirmfoto-2021-11-30-um-21-05-29.png" alt="Bildschirmfoto-2021-11-30-um-21-05-29">
