### ISSUE TITLE
Maskable icon is not being used as a mask 

### ISSUE THREAD

**Issue by gitgauner** [frontendnetwork/veganify#45]
**Describe the bug**
Android doesn't seem to care about the recently added maskable icon in [`07fb237`](https://github.com/JokeNetwork/vegancheck.me/commit/07fb237a8419d8c1dc7d337f69f840d0a7eaedf5).

**To Reproduce**
1. Install the app

**Screenshots**
![image](https://user-images.githubusercontent.com/4144601/144582266-cc0c763c-8e9d-4522-8d88-79cd39f00b22.gif)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4A (via Lambdatest)
 - OS: Android 11
 - Browser: Chrome

**Additional context**
Cache is still deactivated in Cloudflare, devices at lambdatest shouldn't cache anything.

**Comment by philipbrembeck** [comment]
When adding to the homescreen, the icon seems fine, it only does not use the mask on the homescreen itself.
I'll be adding different icon-sizes in the future and keep this issue up to date.
