### ISSUE TITLE
"Close scanner" disappears 

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#46]
Quick video: [https://i.ibb.co/8x1BPNs/ezgif-1-56e02b9f70df.gif](https://i.ibb.co/8x1BPNs/ezgif-1-56e02b9f70df.gif)

_Originally posted by @gitgauner in https://github.com/JokeNetwork/vegancheck.me/issues/44#issuecomment-985339094_

On iOS this works perfectly fine, could someone with an android device confirm this?

**Comment by philipbrembeck** [comment]
https://user-images.githubusercontent.com/4144601/144582082-b0312412-cb33-4e8c-9f77-82a7a9ff02a9.MOV

**Comment by philipbrembeck** [comment]
![image](https://user-images.githubusercontent.com/4144601/144582266-cc0c763c-8e9d-4522-8d88-79cd39f00b22.gif)

**Comment by philipbrembeck** [comment]
@gitgauner Could you please check now? I've pushed an update to the PWA.

**Comment by gitgauner** [comment]
Appears to be working:
![](https://user-images.githubusercontent.com/87610380/144705750-e46ce7bc-095e-4041-88d8-681bc984864d.gif)
