### ISSUE TITLE
Add `user-select: none;`

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#65]

**Comment by gitgauner** [comment]
I don't see this as an enhancement, but more as the opposite, since it would prevent users from copying the results. 
@philipbrembeck please reconsider other design options. 
I know `user-scalable=no` is not up to standards anymore, but could we add it anyway? 

Will close this.

**Comment by philipbrembeck** [comment]
I understand and you're right, but the viewport-option doesn't work on modern phones ([MetaExtension viewport](https://faq.jokenetwork.de/viewport.md)) for accessibility reasons and I also see why.
