### ISSUE TITLE
Add a landscape info section ("Please rotate your device")

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#66]

**Comment by philipbrembeck** [comment]
Related: #60

**Comment by philipbrembeck** [comment]
@gitgauner Please run a quick Lambda-test over the testserver so I can push the solution to the main-branch of the repo.
<img width="1397" alt="Bildschirmfoto 2021-12-22 um 10 00 56" src="https://user-images.githubusercontent.com/4144601/147066119-f9bd3b3e-84b4-4a8a-b19e-63dbc812756d.png">
![Safari Preview Responsive](https://user-images.githubusercontent.com/4144601/147066108-75dba66c-bd2a-45c9-be57-8dbfb535d229.gif)

**Comment by gitgauner** [comment]
@philipbrembeck Looks fine, you're good to go.
