### ISSUE TITLE
Improvements for `$missinginfo`

### ISSUE THREAD

**Issue by gitgauner** [frontendnetwork/veganify#70]
Comment & make comprehensible how `$missinginfo` comes about and document what exactly has to be changed in OFF/OBF to make this string disappear and switch to a valid result page.

```` php
else {
echo '<div class="animated fadeIn">
  <div class="resultborder">
    <span>'.$missinginfo.'</span>
    <p class="missing">
      '.$addinfo.' <a href="https://world.openfoodfacts.org/cgi/product.pl?code='.$barcode.'">'.$editonoff.'</a>.
    </p></span>
    '.$openissue.'
  </div>
</div>'; }
````
(There's a redundant `</span>`-tag!)

Also consider to display the name of the product if available.

**Comment by philipbrembeck** [comment]
While commenting on this, I've found out that `$missinginfo` actually is wrong, we just don't get any information about the Vegan status/palm-oil status, because the array is not set. 
The name and the nutriscore are both available. Will open a new issue with this info.
