### ISSUE TITLE
Localize to Chinese

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#77]
- [x] Evaluate if simplified or traditional or both 
   - [x] Simplified
   - [ ] Traditional
   - [ ] Both
- [ ] Find localizer within @DeepL Network or volunteers 
- [ ] Push

**Comment by gitgauner** [comment]
Let's focus on languages spoken in countries that use the EAN/UPC system.
Closed for now.

**Comment by philipbrembeck** [comment]
Strongly disagree, we get a good amount of requests and unique views from china.

**Comment by gitgauner** [comment]
That's why I reopened it, but no priorization on it.
