### ISSUE TITLE
Add: Secondary EAN Database API

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#79]
Since the OFF/OBF/OPF-API isn't anywhere near complete, we should consider adding a secondary EAN Database API.

The following are the most interesting:

- [x] Look into [eandata.com](https://eandata.com) (Signup required for the API info) [Rating ⭑]
- [x] [Brocade API](http://www.brocade.io/documentation) ([Example for Oreos](https://www.brocade.io/api/items/7622300336738)), gives out only product names, no labels or ingredients [Rating ⭑⭑⭑]
- [x] [Open EAN Database](https://opengtindb.org/api.php) ([Example for Oreos](https://opengtindb.org/?ean=7622300336738&cmd=query&queryid=400000000)), gives out ingredients sometimes, may have to use another API like [hmontazeri/is-vegan](https://github.com/hmontazeri/is-vegan), semi-paid for open-source projects [Rating ⭑⭑⭑⭑]

**Comment by gitgauner** [comment]
Agreed. That has to be done quickly, maybe even in 1.6.
I vote for the third option, but the output in MIME seems quite weird.

**Comment by philipbrembeck** [comment]
Yeah, it seems odd, but it's easily readable with e.g. [$line[2]](https://stackoverflow.com/questions/45323725/get-specific-line-of-web-page-using-file-get-contents).

**Comment by philipbrembeck** [comment]
> maybe even in 1.6.

Will change that to the v1.6 milestone.

**Comment by gitgauner** [comment]
When are you planning to implement one of the APIs? I still like the third option the most since it seems to big a really big db but the 2nd option seems like a good starting point too, if we're planning to direct more people towards Open-x-Facts to add product info.

**Comment by philipbrembeck** [comment]
I'd imagine the Open EAN Database would be great, but the rate limit of 500 could become a problem, since we peaked at ~ 2k visitors a day this month with an average of 900 visits/day.
However, we do not get nearly as much real users which really perform a request, so we're at ~600 requests/day from which 1/4 are empty or nulled (probably requested by bots). 

Empty requests look something like this btw:
```` json
{
		"scan": {
			"code": "",
			"response": {
				"status": "0",
				"api": "0"
			}
		},
		"metadata": {
			"timestamp": {
				"date": "26-01-22",
				"time": "09:34:44pm"
			},
			"debuginfo": {
				"device_type": "mobile",
				"support": {
					"ticket": "61ef******"
				}
			},
			"localization": {
				"lang": "cn",
				"supported_lang": "en"
			}
		}
	}
````
Requests like this should in no case be sent to the mentioned API, since we would easily reach the rate limit in a relatively short time, especially if some botters would use our `script.php` directly as a point of attack. 

> the 2nd option seems like a good starting point too, if we're planning to direct more people towards Open-x-Facts to add product info. 

I like your idea of sending more people to OFF to add ingredients or something else to a product page. The Brocade API should be also much simpler to implement. 

It's gonna be a busy weekend but I'll at least try to implement Brocade. 

EANData however is out of the game, I couldn't find a working API although they're advertising one.

**Comment by philipbrembeck** [comment]
Okay, I just looked into Brocade again and it seems like they do provide ingredients. 
That also means that we indeed could use Brocade as a fallback, if OFF does not have any information at hand. 
With [hmontazeri/is-vegan](https://github.com/hmontazeri/is-vegan), we could extract if the item given is vegan or not. Will open a new issue for that.

**Comment by gitgauner** [comment]
Thank you for the request insight. 
Maybe we should think about documenting the function of the `script.php` and the corresponding JSON responses written to the/generated by the API (?) in a wiki or a blog post. 

Since all tasks are done in this issue and you moved the now main subject brocade.io to #80 I'll close this issue for now.

> we could extract if the item given 

Extract wahrscheinlich oder 😂

**Comment by philipbrembeck** [comment]
@gitgauner _Aaaaa halts maul :D_

The JSON responses are generated by the [vegancheck-stats-api](https://github.com/JokeNetwork/vegancheck-stats-api) and are mostly relevant for debugging (and finding out if we need to limit request or so) but we could write an article about that.
