### ISSUE TITLE
Fallback API Integration for OFF (Tracker)

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#80]
URI: [ferrisoxide/brocade.io](https://github.com/ferrisoxide/brocade.io)

_Originally posted by @philipbrembeck in https://github.com/JokeNetwork/vegancheck.me/issues/79#issuecomment-1022504334_

> Okay, I just looked into Brocade again and it seems like they do provide ingredients. 
That also means that we indeed could use Brocade as a fallback, if OFF does not have any information at hand. 
> With [hmontazeri/is-vegan](https://github.com/hmontazeri/is-vegan), we could extract if the item given is vegan or not.

## Tasks/Roadmap
- [x] #81 
- [x] #82

**Comment by gitgauner** [comment]
Since this is getting more than we anticipated, I'll split this into different issues tracked here.
