### ISSUE TITLE
Integrate Brocade.io as a fallback for OFF

### ISSUE THREAD

**Issue by gitgauner** [frontendnetwork/veganify#81]
URI: ferrisoxide/brocade.io

Integrate Brocade.io as a Fallback for OFF

- [x] Test integration 
   - [x] Find matching if-cause to use the alternate API
   - [x] Test on test server
- [x] Git Push
- [x] Productive Integration

**Comment by philipbrembeck** [comment]
Example item (all fields used): [Nutella](https://www.brocade.io/api/items/00009800895007)
