### ISSUE TITLE
Integrate Open EAN Database as a secondary fallback / Encourage more people to contribute to OFF

### ISSUE THREAD

**Issue by gitgauner** [frontendnetwork/veganify#83]
## What?
For when the Brocade.io API has no result either, we should add a third DB just in case.
My pledge would be Open EAN Database, since we could use their public key, when we're expecting so few requests.

[Open EAN Database](https://opengtindb.org/api.php) ([Example for Oreos](https://opengtindb.org/?ean=7622300336738&cmd=query&queryid=400000000)), gives out ingredients sometimes but in a not computable format

## Roadmap
- [x] #84
   (using @philipbrembeck's idea of [$line[2]](https://stackoverflow.com/questions/45323725/get-specific-line-of-web-page-using-file-get-contents) since the API does not give out JSON)

## Products to test

````
$ curl https://opengtindb.org/?ean=42227526&cmd=query&queryid=400000000
````
for Gizeh Rolling Papers (vegan btw). They're not in any of the other APIs.

Answer: 
````

error=0
---
asin=
name=Drehpapier
detailname=Gizeh Fine
vendor=Gizeh
maincat=Raucherwaren
subcat=Zubehör
maincatnum=18
subcatnum=3
contents=0
pack=0
origin=-
descr=100er Pack mit Magnetverschluß, 18,5 g/m²
name_en=
detailname_en=
descr_en=
validated=75 %
---
asin=
name=Drehpapier
detailname=Gizeh Fine
vendor=Gizeh
maincat=Raucherwaren
subcat=Zubehör
maincatnum=18
subcatnum=3
contents=384
pack=324
origin=-
descr=100er Pack mit Magnetverschluß, 18,5 g/m²
name_en=
detailname_en=
descr_en=
validated=25 %
---
````

The name of the product is always provided in the fifth line of the response, the response code is always in line 1.

Other codes: 4002604009256

**Comment by philipbrembeck** [comment]
I'm getting a stroke with this api wth

**Comment by philipbrembeck** [comment]
I did come up with this now, since every other option I tried wouldn't work:
````php
$OEDBAPI = file('https://opengtindb.org/?ean=42227526&cmd=query&queryid=400000000');
$status = $OEDBAPI[1];
parse_str($OEDBAPI[5], $output);
$name = $output['detailname'];

if (str_contains($status, "error=0")){
	echo $name;
}
else {
	
}
````
It's really horrible as it depends on the lines staying the same every time, but it works, at least 😏 
My original attempt was to use `parse_str()` but no way 😅
