### ISSUE TITLE
Replace `file_get_contents` with cURL

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#88]
I've found that performance-wise, cURL makes no difference, but to be up to our standards I'll implement it over time. 
This might blow up the code a bit, so I'm thinking about restructuring it.

- [x] Replace in `script.php`
- [x] API
  - [x] Replace in API
  - [x] Replace in API documentation

**Comment by philipbrembeck** [comment]
API docs updated:
> 
> ````php
>  // Call with file_get_contents() [Discouraged]
>  ````

>````php
><?php
> // Call with cURL
>$url = "https://vegancheck.me/api/v0/product?product=12345";
>
> $curl = curl_init($url);
>curl_setopt($curl, CURLOPT_URL, $url);
>curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
>
>$headers = array(
>   "AUTH-KEY: alpha",
>);
>curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
>
>$resp = curl_exec($curl);
>curl_close($curl);
>
>$data = json_decode($resp);
>$status = $data->status;
>
>if ($status == "200"){
>	echo $data->data->name.' '.$data->data->is_vegan;
>}
>elseif ($status == "404"){
>	echo "Not found in database!";
>}
>elseif ($status == "429"){
>	echo "Ratelimit exceeded for today :(";
>}
>?>
>````
in [Wiki](https://github.com/JokeNetwork/vegancheck.me/wiki) / [Docs](https://jokenetwork.de/vegancheck-api)

**Comment by gitgauner** [comment]
Was just about to say cURL would make no difference when we are only doing GET requests besides more lines but you're right, f_g_c is always marked as discouraged.
Great work on the api!

**Comment by philipbrembeck** [comment]
Also replaced in API. Closed.

**Comment by philipbrembeck** [comment]
The OpenEANDB is still adressed with file(): 
>````php
>$OEDBAPI = file('https://opengtindb.org/?ean='.$barcode.'&cmd=query&queryid=400000000');
>$status = $OEDBAPI[1];
>````
This is because we were unaware of `parse_ini_string`. Will fix soon.
